### PR TITLE
fix(php) - bug

### PR DESCRIPTION
**Pull request by ttodua**

### CODE REVIEW

**Comment by carlosmiei** [comment]
@ttodua tests fail here 🤔

**Comment by ttodua** [comment]
> @ttodua tests fail here 🤔

but this merger doesn't break other tests, we should fix them separately imo

**Comment by ttodua** [comment]
will push soon

**Comment by ttodua** [comment]
@carlosmiei unfortunately I've spent quite a lot on this, and i think there is some kind of caching, as the tests are failing with different reason on my local and here too sometimes, and when i close & reopen the PR, the specific test does not break (because uses latest pushed version of file, compared to previous run of tests).

anyway, atm this PR passes, and the error happening there is unrelated to this

**Pull request merged**
