### PR TITLE
feat(php) - object.keys & object.values fix

### PR DESCRIPTION
**Pull request by ttodua**
in all other langs, the type is not checked and blindly goes with getting `.Keys`. in php we should also do same -  if not array, assume object

### CODE REVIEW

**Comment by carlosmiei** [comment]
can you give a practical example that this fixes?

**Comment by ttodua** [comment]
> can you give a practical example that this fixes?

iirc I have met this problem when i worked on tests (because our tests are transpiled with asst), and for JS, any unified ccxt structure is `object`, eg `orderbook` and `ws ordebook`. however, in php it's not same, one of them is array and another is object. so, having `Object.keys()` works for JS for all case, but in php it should be able to get keys/values from objects too.

**Comment by carlosmiei** [comment]
@ttodua I'm still a bit confused, `Object.keys` should only be used in dictionaries right? and in PHP arrays might also be dicts. Maybe would be easier with an example

**Comment by ttodua** [comment]
object keys are not to be applied only dictionaries. it might be very ccxt specific, but ast-transpiler is more generic.
even say ccxt, there are `orderbook` structure which is dict, but `ws` orderbook which is somewhat cache-based object, in php they are two different types, regular OB is array, while ws OB is some object

**Comment by ttodua** [comment]
so, when we wanted to test out the orderbook result in ccxt tests, we cant apply `Object.keys` on them normally, because in js it worked (as JS doesnt matter if it's orderbook returned from fetchOrderBook or watchOrderBook) while php broke for watchOrderBook tests, as it couldnt apply Object.keys or returned WS orderbook object.

**Comment by carlosmiei** [comment]
@ttodua I think that Object.keys is only to be applied to dictionaries or similar structures if we want to keep the syntax generic across languages no?

**Comment by ttodua** [comment]
I don't think so, as long as Object.keys in javascript works for all kinds (dictionary like types and also regular objects) why not make it work in php for 'dictionaries' (associative arrays) and for regular stdClass objects too? so why shouldn't astt get keys from  stdClass obj, eg: https://onlinephp.io/c/c7973 if Object.keys in JS can get keys from both kind of type ('assoc array' & obj)

**Comment by ttodua** [comment]
i can't think a case when supporting objects for php would harm astt use-cases, other than benefiting, but if i miss some context, as you decide. (on top of the fact we wouldnt have a support for WS objects in ccxt)

**Comment by carlosmiei** [comment]
@ttodua Because I'm not sure we can generalize that behavior for c#/go etc (btw go is merged in master so now we have to take it into consideration)

**Comment by ttodua** [comment]
what should we do for ccxt so? in php WS tests

**Comment by carlosmiei** [comment]
maybe we need a "custom" non transpilable function there

**Pull request closed without merging**
